enableRobotsTXT = true
BaseURL			="https://nextwavesolutions.io/"
LanguageCode		="US-EN"
Title			="NextWave Solutions"
paginate 		= 5
pluralizelisttitles 	= false
DisqussShortname 	="Justyn Temme"
Copyright 		="All rights reserved - 2017"
canonifyurls 		=true
theme			="gohugo-amp"

[params]
	amp = true
	ampElements = ["amp-accordion","amp-analytics","amp-app-banner","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]

	themeColor = "blue"
	googleAnalytics = "UA-109147161-1"
	ampManifest = "/manifest.json"

	alternatePageName = "NextWave Solutions"
	organisationName = "NextWave Solutions"
	socialProfiles = ["https://twitter.com/nextwavesllc"]
	description 	= "NextWave Solutions LLC"
	cover 		= "images/Love-Coding.png"
	author		= "Justyn Temme"
	authorlocation	= "United States of America"
	authorwebsite	= "https://nextwavesolutions.io"
	authorbio	= "Open Source Developer"
	githubName	= "justyntemme"
	twitterName	= "nextwavesllc"	
	linkedinName	= "justyntemme"
[[menu.main]]
	name		= "Github repos"
	weight		= -150
	identifier	= "github"
	url		= "https://github.com/justyntemme/"	
[[menu.main]]
	name		= "Home"
	weight		= 100
	identifier	= "home"
	url		= "/"
[[menu.main]]
	name		= "Blog"
	weight		= 99
	identifier	= "blog"
	url		= "/#content"		
